name: .NET Core and Framework test and publish to NuGet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Setup Nuget.exe
    #   uses: warrenbuckley/Setup-Nuget@v1

    # - name: Restore packages
    #   run: nuget restore

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build with MSBuild
      run: msbuild -p:Configuration=Release

    - name: Run tests
      run: dotnet test --no-build